//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTube.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Comment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comment()
        {
            this.CommentRatings = new HashSet<CommentRating>();
        }

        public long CommentID { get; set; }
        public Nullable<long> VideoID { get; set; }
        public string CommentOwner { get; set; }
        [Required]
        [Display(Name = "Text")]
        public string CommentText { get; set; }
        public System.DateTime DatePosted { get; set; }
        public long LikesCount { get; set; }
        public long DislikesCount { get; set; }
        public bool Deleted { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentRating> CommentRatings { get; set; }
        public virtual User User { get; set; }
        public virtual Video Video { get; set; }
    }
}
