//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTube.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentRating
    {
        public long LikeID { get; set; }
        public string LikeOwner { get; set; }
        public Nullable<long> CommentId { get; set; }
        public bool IsLike { get; set; }
        public System.DateTime LikeDate { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual User User { get; set; }
    }
}
