//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTube.Models
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.CommentRatings = new HashSet<CommentRating>();
            this.Comments = new HashSet<Comment>();
            this.Subscribers = new HashSet<Subscriber>();
            this.Subscribers1 = new HashSet<Subscriber>();
            this.VideoRatings = new HashSet<VideoRating>();
            this.Videos = new HashSet<Video>();
        }
        [Display(Name = "Username")]
        [Required]
        public string Username { get; set; }

        [Required]
        [Display(Name = "Password")]
        public string Pass { get; set; }
        [Required]
        [Display(Name = "First name")]
        public string Firstname { get; set; }
        [Required]
        [Display(Name = "Last name")]
        public string Lastname { get; set; }

        [Display(Name = "User type")]
        public string UserType { get; set; }

        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Display(Name = "Description")]
        public string UserDescription { get; set; }

        [Display(Name = "Reg. Date")]
        public System.DateTime RegistrationDate { get; set; }

        [Display(Name = "Blocked")]
        public bool Blocked { get; set; }

        [Display(Name = "Deleted")]
        public bool Deleted { get; set; }

        [Display(Name = "Profile Url")]
        public string ProfilePictureUrl { get; set; }

        public long SubscribersCount { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentRating> CommentRatings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subscriber> Subscribers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subscriber> Subscribers1 { get; set; }
        public virtual UserType UserType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VideoRating> VideoRatings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Video> Videos { get; set; }

        private static SelectList usersSortOrder = new SelectList(new List<SelectListItem>
            {
                new SelectListItem { Selected = true, Text = "Username ASC", Value = "username_asc"},
                new SelectListItem { Selected = false, Text = "Username DESC", Value = "username_desc"},
                new SelectListItem { Selected = false, Text = "First Name ASC", Value = "firstname_asc"},
                new SelectListItem { Selected = false, Text = "First Name DESC", Value = "firstname_desc"},
                new SelectListItem { Selected = false, Text = "Last Name ASC", Value = "lastname_asc"},
                new SelectListItem { Selected = false, Text = "Last Name DESC", Value = "lastname_desc"},
                new SelectListItem { Selected = false, Text = "Email ASC", Value = "email_asc"},
                new SelectListItem { Selected = false, Text = "Email DESC", Value = "email_desc"},
                new SelectListItem { Selected = false, Text = "User type ASC", Value = "user_type_asc"},
                new SelectListItem { Selected = false, Text = "User type DESC", Value = "user_type_desc"},
                new SelectListItem { Selected = false, Text = "Status ASC", Value = "status_asc"},
                new SelectListItem { Selected = false, Text = "Status DESC", Value = "status_desc"}
            }, "Value", "Text", 1);
        public static SelectList UsersSortOrder() { return usersSortOrder; }

    }
}
