//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTube.Models
{
    public partial class VideoRating
    {
        public long LikeID { get; set; }
        public long VideoID { get; set; }
        public string LikeOwner { get; set; }
        public bool IsLike { get; set; }
        public System.DateTime LikeDate { get; set; }
        public bool Deleted { get; set; }

        public virtual User User { get; set; }
        public virtual Video Video { get; set; }
    }
}
